// Build steps for the CLI's local UI (the legacy prototype served by
// `factstack ui` and inlined by `export` / `quick`). Shared by
// scripts/sync-ui.mjs and scripts/test/legacy-ui.test.ts so the test checks
// exactly what ships. Everything the page needs ends up local:
//   - Tailwind v4 utilities compiled with the installed @tailwindcss/cli and
//     inlined (the prototype used the in-browser JIT from cdn.jsdelivr.net);
//   - @babel/parser bundled with esbuild into vendor/babel-parser.mjs, which
//     the ui server serves (the prototype used esm.sh);
//   - any remaining remote import() (the optional Supabase client) replaced
//     by an inert rejection, so the CLI build can never fetch it.

import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

export const CLI_ROOT = resolve(here, '..', '..');
export const PROTOTYPE_SRC = resolve(CLI_ROOT, '..', '..', 'legacy', 'prototype', 'index.html');
export const TAILWIND_INPUT = resolve(CLI_ROOT, 'scripts', 'ui-tailwind.css');
export const DATA_PLACEHOLDER = '__INLINE_FACTSTACK_JSON__';
const TAILWIND_MARKER = '<style id="facts-tailwind"></style>';
const DATA_OPEN = '<script id="factstack-data" type="application/json">';
const GENERATED_BANNER =
  '<!-- GENERATED by apps/cli/scripts/sync-ui.mjs from legacy/prototype/index.html. ' +
  'Edit the source, then run `pnpm --filter @factstack/cli sync:ui`. -->';

/** Compile the prototype's Tailwind utilities (minified CSS string). */
export function compileTailwind() {
  const pkgPath = require.resolve('@tailwindcss/cli/package.json');
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  const bin = resolve(
    dirname(pkgPath),
    typeof pkg.bin === 'string' ? pkg.bin : pkg.bin.tailwindcss,
  );
  const css = execFileSync(process.execPath, [bin, '--input', TAILWIND_INPUT, '--minify'], {
    cwd: CLI_ROOT,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
    maxBuffer: 64 * 1024 * 1024,
  }).trim();
  if (!css.includes('@layer utilities')) throw new Error('tailwindcss produced no utilities layer');
  return css;
}

/** Bundle @babel/parser into one browser ES module (source string). */
export async function bundleBabelParser() {
  const { build } = await import('esbuild');
  const pkgPath = require.resolve('@babel/parser/package.json');
  const { version } = JSON.parse(readFileSync(pkgPath, 'utf8'));
  const license = readFileSync(resolve(dirname(pkgPath), 'LICENSE'), 'utf8').trim();
  const out = await build({
    stdin: {
      contents: "export { parse, parseExpression } from '@babel/parser';",
      resolveDir: here,
      loader: 'js',
    },
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2020',
    minify: true,
    write: false,
    legalComments: 'none',
    logLevel: 'silent',
    banner: {
      js: `/*! @babel/parser ${version}, vendored for the factstack CLI UI by apps/cli/scripts/sync-ui.mjs.\n${license.replaceAll('*/', '* /')}\n*/`,
    },
  });
  return out.outputFiles[0].text;
}

/** Replace the body of the inline dataset block. */
export function replaceDataBlock(html, body) {
  const i = html.indexOf(DATA_OPEN);
  if (i < 0) throw new Error('inline data block not found in prototype');
  const after = i + DATA_OPEN.length;
  const end = html.indexOf('</script>', after);
  if (end < 0) throw new Error('inline data block is not closed');
  return html.slice(0, after) + body + html.slice(end);
}

/** Resource-loading constructs that would reach the network. Plain links
 *  (<a href>) and the user-initiated GitHub API fetches are not resources. */
const REMOTE_RESOURCE_PATTERNS = [
  /<script\b[^>]*\bsrc\s*=\s*["']?(?:https?:)?\/\//i,
  /<link\b[^>]*\bhref\s*=\s*["']?(?:https?:)?\/\//i,
  /@import\s+(?:url\()?\s*["']?(?:https?:)?\/\//i,
  /url\(\s*["']?(?:https?:)?\/\//i,
  /\bimport\s*\(\s*["'`](?:https?:)?\/\//i,
  /\bfrom\s+["'](?:https?:)?\/\//i,
  /fonts\.googleapis\.com|fonts\.gstatic\.com|cdn\.jsdelivr\.net|esm\.sh\/|unpkg\.com|cdnjs\.cloudflare\.com/i,
];

/** Throws if the page would load anything from another origin. */
export function assertNoRemoteResources(html) {
  for (const re of REMOTE_RESOURCE_PATTERNS) {
    const m = re.exec(html);
    if (m) {
      const line = html.slice(0, m.index).split('\n').length;
      throw new Error(`remote resource reference at line ${line}: ${m[0]}`);
    }
  }
}

/** Turn the prototype source into the self-contained CLI template. */
export function buildTemplate(source, { tailwindCss }) {
  if (!source.includes(TAILWIND_MARKER)) throw new Error(`prototype is missing ${TAILWIND_MARKER}`);
  if (/<\/style/i.test(tailwindCss)) throw new Error('compiled CSS contains </style');
  let html = source.replace(
    TAILWIND_MARKER,
    () => `<style id="facts-tailwind">${tailwindCss}</style>`,
  );
  html = html.replaceAll(
    /import\(\s*['"]https?:\/\/[^'"]+['"]\s*\)/g,
    "Promise.reject(new Error('Remote modules are disabled in the factstack CLI build.'))",
  );
  // Ship the placeholder, not the playground's baked sample dataset: every
  // CLI path injects real data, and the sample carries a stale local path.
  html = replaceDataBlock(html, DATA_PLACEHOLDER);
  html = html.replace(/^<!doctype html>/i, (m) => `${m}\n${GENERATED_BANNER}`);
  assertNoRemoteResources(html);
  return html;
}
