/**
 * Which files FACTS may overwrite, and which skill folder a project gets.
 *
 * FSB-7 (owner decision 2026-09-24): a hand-written `.cursorrules` or
 * `.github/copilot-instructions.md` is never overwritten — only a file
 * carrying the FACTS-managed marker (or the pre-marker "Auto-generated by
 * FACTS" footer) is refreshed. Browser Save used to replace a team's rules
 * wholesale, and after a GitHub scan wrote ANOTHER repo's rules into the
 * picked folder.
 *
 * FSB-11: the Claude skill folder must not depend on which host named the
 * project — the CLI says `repo`, a browser GitHub scan `owner/repo@ref`.
 */
import { describe, expect, it } from 'vitest';
import {
  buildSkillsTo,
  claudeRenderer,
  copilotRenderer,
  cursorRenderer,
  agentToSkillSpec,
  FACTS_MANAGED_MARKER,
  isFactsManaged,
} from '../src/index.js';
import { MemoryFileWriter } from './helpers/memory-writer.js';
import { makeAgent, makeHuman } from './helpers/fixtures.js';

const HAND_CURSOR = 'Always use tabs. Our API lives in /srv.\n';
const HAND_COPILOT = '# Team rules\nWe write Go, not TypeScript.\n';

function seeded(files: Record<string, string>): MemoryFileWriter {
  const w = new MemoryFileWriter();
  for (const [p, b] of Object.entries(files)) w.files.set(p, b);
  return w;
}

const reader = (w: MemoryFileWriter) => async (p: string) => w.get(p) ?? null;

describe('FSB-7 — hand-written rules files are never overwritten', () => {
  it('keeps hand-written .cursorrules and Copilot instructions on a default save', async () => {
    const w = seeded({
      '.cursorrules': HAND_CURSOR,
      '.github/copilot-instructions.md': HAND_COPILOT,
    });
    const r = await buildSkillsTo(w, makeAgent(), makeHuman(), undefined, {
      preserveExisting: ['agents'],
      readExisting: reader(w),
    });
    expect(w.get('.cursorrules')).toBe(HAND_CURSOR);
    expect(w.get('.github/copilot-instructions.md')).toBe(HAND_COPILOT);
    expect(r.preserved).toEqual(
      expect.arrayContaining(['.cursorrules', '.github/copilot-instructions.md']),
    );
    expect(r.files).not.toHaveProperty('.cursorrules');
  });

  it('keeps them even when the format is requested explicitly', async () => {
    const w = seeded({ '.cursorrules': HAND_CURSOR });
    const r = await buildSkillsTo(w, makeAgent(), makeHuman(), ['cursor'], {
      readExisting: reader(w),
    });
    expect(w.get('.cursorrules')).toBe(HAND_CURSOR);
    expect(r.preserved).toEqual(['.cursorrules']);
  });

  it('keeps them when the writer cannot read (safe side)', async () => {
    const w = seeded({ '.cursorrules': '<!-- factstack:managed -->\nold' });
    const r = await buildSkillsTo(w, makeAgent(), makeHuman(), ['cursor']);
    expect(w.get('.cursorrules')).toBe('<!-- factstack:managed -->\nold');
    expect(r.preserved).toEqual(['.cursorrules']);
  });

  it('refreshes a file FACTS wrote — marked, or with the pre-marker footer', async () => {
    const legacy = 'You are working in x.\n<!-- Auto-generated by FACTS · factstack 0.1.0 -->\n';
    const w = seeded({
      '.cursorrules': `stale\n<!-- ${FACTS_MANAGED_MARKER} -->\n`,
      '.github/copilot-instructions.md': legacy,
    });
    const r = await buildSkillsTo(w, makeAgent(), makeHuman(), ['cursor', 'copilot'], {
      readExisting: reader(w),
    });
    expect(r.preserved).toEqual([]);
    expect(w.get('.cursorrules')).toContain('You are working in the **demo** codebase');
    expect(w.get('.github/copilot-instructions.md')).toContain('# demo');
  });

  it('reads through a writer that exposes readText when no reader is passed', async () => {
    const w = seeded({ '.cursorrules': `x\n<!-- ${FACTS_MANAGED_MARKER} -->\n` });
    const readable = Object.assign(w, { readText: reader(w) });
    const r = await buildSkillsTo(readable, makeAgent(), makeHuman(), ['cursor']);
    expect(r.preserved).toEqual([]);
    expect(w.get('.cursorrules')).toContain('**demo**');
  });

  it('every generated .cursorrules / Copilot file carries the marker', () => {
    const spec = agentToSkillSpec(makeAgent(), makeHuman());
    expect(isFactsManaged(cursorRenderer.render(spec)['.cursorrules']!)).toBe(true);
    const copilot = copilotRenderer.render(spec)['.github/copilot-instructions.md']!;
    expect(copilot).toContain(FACTS_MANAGED_MARKER);
    expect(isFactsManaged(HAND_CURSOR)).toBe(false);
  });
});

/**
 * A writer that behaves like NTFS / APFS: names are case-insensitive, and a
 * write to `AGENTS.md` lands on (replaces) an existing `agents.md`.
 */
class CaseInsensitiveWriter extends MemoryFileWriter {
  override async writeText(p: string, body: string): Promise<number> {
    const same = [...this.files.keys()].find((k) => k.toLowerCase() === p.toLowerCase());
    if (same !== undefined) this.files.delete(same);
    return super.writeText(p, body);
  }
}

/* The existence check was exact-case, so on Windows/macOS a write of
   AGENTS.md replaced a hand-written agents.md, and a mixed-case Copilot file
   skipped the managed-marker check. */
describe('an existing file is found whatever its case', () => {
  it('keeps a hand-written lowercase agents.md (never-overwrite default)', async () => {
    const w = new CaseInsensitiveWriter();
    w.files.set('agents.md', '# our own agent notes\n');
    const r = await buildSkillsTo(w, makeAgent(), makeHuman(), ['agents'], {
      preserveExisting: ['agents'],
    });
    expect(w.get('agents.md')).toBe('# our own agent notes\n');
    expect(w.has('AGENTS.md')).toBe(false);
    expect(r.preserved).toEqual(['AGENTS.md']);
  });

  it('keeps a hand-written mixed-case Copilot file', async () => {
    const w = new CaseInsensitiveWriter();
    w.files.set('.github/Copilot-Instructions.md', HAND_COPILOT);
    const r = await buildSkillsTo(w, makeAgent(), makeHuman(), ['copilot'], {
      readExisting: reader(w),
    });
    expect(w.get('.github/Copilot-Instructions.md')).toBe(HAND_COPILOT);
    expect(r.preserved).toEqual(['.github/copilot-instructions.md']);
  });

  it('reads the marker from the on-disk name, so a managed mixed-case file refreshes', async () => {
    const w = new CaseInsensitiveWriter();
    w.files.set('.github/Copilot-Instructions.md', `stale\n<!-- ${FACTS_MANAGED_MARKER} -->\n`);
    const r = await buildSkillsTo(w, makeAgent(), makeHuman(), ['copilot'], {
      readExisting: reader(w),
    });
    expect(r.preserved).toEqual([]);
    expect(w.get('.github/copilot-instructions.md')).toContain('# demo');
  });
});

describe('FSB-11 — one Claude skill folder per project, whichever host named it', () => {
  const skillPath = (name: string): string => {
    const agent = makeAgent({ project: { ...makeAgent().project, name } });
    return Object.keys(claudeRenderer.render(agentToSkillSpec(agent, makeHuman())))[0]!;
  };

  it('a GitHub scan (owner/repo@ref) and the CLI (repo) write the same SKILL.md', () => {
    expect(skillPath('factstack')).toBe('.claude/skills/factstack-factstack/SKILL.md');
    expect(skillPath('adi/factstack@main')).toBe('.claude/skills/factstack-factstack/SKILL.md');
    expect(skillPath('adi/factstack')).toBe('.claude/skills/factstack-factstack/SKILL.md');
  });

  it('leaves an ordinary folder name alone, even one containing @', () => {
    expect(skillPath('my@proj')).toBe('.claude/skills/factstack-my-proj/SKILL.md');
  });
});
