/**
 * Bundled demo dataset loader — the zero-setup first-run experience.
 *
 * The demo is a pre-baked VizArtifact (FactStack analyzing itself, doc bodies
 * stripped) shipped at `demo/factstack.json`. Generated by scripts/make-demo.mjs.
 */
import type { Dataset, LoadedDataset } from './types.ts';
import { assetUrl } from './chromeEnv.ts';

export async function loadDemo(): Promise<LoadedDataset> {
  const res = await fetch(assetUrl('demo/factstack.json'));
  if (!res.ok) throw new Error(`Demo dataset unavailable (${res.status})`);
  const dataset = (await res.json()) as Dataset;
  // The cast is a promise, not a proof — validate the load-bearing shape the
  // routes dereference (tree/project/stats) before handing it to the UI.
  if (!dataset || typeof dataset !== 'object' || !dataset.tree || !dataset.project || !dataset.stats) {
    throw new Error('Demo dataset is malformed.');
  }
  return {
    dataset,
    source: { kind: 'demo', label: dataset.project?.name ?? 'demo', at: Date.now() },
  };
}
