/**
 * `.facts/MEMORY.md` generator — v0.3.1.
 *
 * Compact, deterministic markdown brief that AI agents read FIRST when
 * joining a project. Synthesizes the highest-signal slices of agent.json
 * + human.json into a 2-10 KB file an agent can hold in context for the
 * entire session, replacing the 40-200 KB cold-read of agent.json.
 *
 * Design contract (enforced by `packages/core/test/memory.test.ts`):
 *   - PURE function: no Date.now(), no Math.random(), no Node imports.
 *   - DETERMINISTIC: byte-identical output for byte-identical input.
 *   - ORDERED sections: agents read top-down; ordering is part of the
 *     contract.
 *   - SECTION OMISSION over EMPTY SECTIONS: when a section has nothing
 *     to render, omit the heading entirely (keeps the artifact small
 *     and the structure unambiguous).
 *   - SIZE-BOUNDED: empty fixture < 2 KB; large fixture < 10 KB. The
 *     caps below (top-3 langs, max-8 frameworks, max-8 risks, max-5
 *     active files, max-12 routes) defend that budget.
 */

import type { AgentArtifact, HumanArtifact, Risk } from '@factstack/spec';

export const MEMORY_SCHEMA_VERSION = 'factstack-memory.v1' as const;

const TRUNCATE_FRAMEWORKS = 8;
const TRUNCATE_RISKS = 8;
const TRUNCATE_ACTIVITY = 5;
const TRUNCATE_KEY_FILES = 8;
const TRUNCATE_ROUTES_PER_GROUP = 6;
const TRUNCATE_CAPABILITIES = 6;
const ONELINER_MAX_LEN = 280;

/**
 * Render a MEMORY.md brief for the given analysis.
 *
 * Caller (CLI / MCP server) is responsible for writing to disk. This
 * module stays isomorphic — no Node imports.
 */
export function buildMemory(agent: AgentArtifact, human: HumanArtifact): string {
  const sections: string[] = [];

  // ── Header ────────────────────────────────────────────────────────
  sections.push(`# ${agent.project.name}`);
  sections.push('');
  /* v0.3.10 — prefer the deterministic intent sentence (composes
     monorepo + frameworks + apps into one line), fall back to the
     oneLiner only when intent is null/missing/empty. Use `||`
     (not `??`) so empty-string intent triggers the fallback —
     pre-v0.3.10 fixtures set intent: '' as a placeholder and we
     don't want them to render as a blank blockquote. */
  const headline = (human.summary.intent && human.summary.intent.length > 0)
    ? human.summary.intent
    : human.summary.oneLiner;
  sections.push(`> ${normalizeOneLiner(headline)}`);
  sections.push('');
  sections.push(
    `<!-- Auto-generated by FACTS · do not edit by hand. Run \`factstack analyze\` to refresh. -->`,
  );
  sections.push(
    `<!-- ${MEMORY_SCHEMA_VERSION} · generated ${agent.generatedAt} · ` +
      `${agent.stats.fileCount} files · ${formatTokens(agent.stats.totalTokenCost)} tokens -->`,
  );

  // ── At a glance ───────────────────────────────────────────────────
  sections.push('');
  sections.push('## At a glance');
  sections.push('');
  const langs = topLanguages(agent);
  if (langs.length) {
    sections.push(`- **Languages**: ${langs.map((l) => `${l.id} (${l.pct}%)`).join(', ')}`);
  }
  const fws = (agent.project.frameworks ?? []).filter(Boolean);
  if (fws.length) {
    const shown = fws.slice(0, TRUNCATE_FRAMEWORKS).join(', ');
    const more = fws.length > TRUNCATE_FRAMEWORKS ? ` (+${fws.length - TRUNCATE_FRAMEWORKS} more)` : '';
    sections.push(`- **Frameworks**: ${shown}${more}`);
  }
  sections.push(
    `- **Stats**: ${formatNum(agent.stats.fileCount)} files · ` +
      `${formatNum(agent.stats.loc)} LOC · ${formatTokens(agent.stats.totalTokenCost)} tokens`,
  );
  sections.push(`- **Health**: ${human.summary.health.headline}`);
  if (agent.stats.fileCount === 0) {
    sections.push('');
    sections.push('_No source files yet — analyze a populated project to fill out this brief._');
  }

  // ── Capabilities ──────────────────────────────────────────────────
  if (agent.capabilities.length) {
    sections.push('');
    sections.push('## Capabilities');
    sections.push('');
    for (const cap of agent.capabilities.slice(0, TRUNCATE_CAPABILITIES)) {
      sections.push(`- ${cap}`);
    }
  }

  // ── Entry points ──────────────────────────────────────────────────
  const eps = (agent.project.entryPoints ?? []).filter(Boolean);
  if (eps.length) {
    sections.push('');
    sections.push('## Entry points');
    sections.push('');
    for (const ep of eps.slice(0, 5)) sections.push(`- \`${ep}\``);
  }

  // ── Routes (grouped by framework, alphabetical, capped per group) ─
  const routes = agent.routes ?? [];
  if (routes.length) {
    sections.push('');
    sections.push('## Routes');
    sections.push('');
    // Group by framework
    const groups = new Map<string, typeof routes>();
    for (const r of routes) {
      const key = r.framework || '(unknown)';
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key)!.push(r);
    }
    const sortedFrameworks = [...groups.keys()].sort((a, b) => a.localeCompare(b));
    for (const fw of sortedFrameworks) {
      sections.push(`### ${fw}`);
      sections.push('');
      const list = groups.get(fw)!.slice().sort((a, b) => (a.path || '').localeCompare(b.path || ''));
      for (const r of list.slice(0, TRUNCATE_ROUTES_PER_GROUP)) {
        sections.push(`- ${r.method ?? 'GET'} \`${r.path}\``);
      }
      if (list.length > TRUNCATE_ROUTES_PER_GROUP) {
        sections.push(`- _+${list.length - TRUNCATE_ROUTES_PER_GROUP} more in this group_`);
      }
      sections.push('');
    }
  }

  // ── Key files (highest in-degree = most-imported = hubs) ──────────
  const keyFiles = topImportedFiles(agent, TRUNCATE_KEY_FILES);
  if (keyFiles.length) {
    sections.push('');
    sections.push('## Key files');
    sections.push('');
    sections.push('Files most-imported by the rest of the codebase — read these first to understand the API surface.');
    sections.push('');
    for (const k of keyFiles) {
      sections.push(`- \`${k.path}\` (imported by ${k.inDegree})`);
    }
  }

  // ── Open risks (only severity high+ — anything lower is noise here) ──
  const openRisks = (agent.risks ?? []).filter(
    (r): r is Risk => r != null && (r.severity === 'high' || r.severity === 'critical'),
  );
  if (openRisks.length) {
    sections.push('');
    sections.push('## Open risks');
    sections.push('');
    const shown = openRisks.slice(0, TRUNCATE_RISKS);
    for (const r of shown) {
      const sev = r.severity === 'critical' ? '🔴 **CRITICAL**' : '🟠 **HIGH**';
      const loc = r.file ? ` · \`${r.file}${r.line != null ? `:${r.line}` : ''}\`` : '';
      sections.push(`- ${sev} ${r.category}${loc} — ${r.message}`);
    }
    if (openRisks.length > TRUNCATE_RISKS) {
      sections.push(`- _+${openRisks.length - TRUNCATE_RISKS} more high/critical risks_`);
    }
  }

  // ── Recently active files ────────────────────────────────────────
  if (human.activity.length) {
    sections.push('');
    sections.push('## Recently active files');
    sections.push('');
    for (const a of human.activity.slice(0, TRUNCATE_ACTIVITY)) {
      sections.push(`- \`${a.file}\``);
    }
  }

  // ── How to read this codebase (deterministic 5-step tour) ────────
  sections.push('');
  sections.push('## How to read this codebase');
  sections.push('');
  sections.push('A 5-step deterministic tour for new agents and engineers:');
  sections.push('');
  const tour = buildTour(agent);
  for (let i = 0; i < tour.length; i++) {
    sections.push(`${i + 1}. **${tour[i]!.label}** — ${tour[i]!.value}`);
  }

  // ── Footer ────────────────────────────────────────────────────────
  sections.push('');
  sections.push('---');
  sections.push('');
  sections.push(`<!-- factstack-memory schema=${MEMORY_SCHEMA_VERSION} -->`);

  return sections.join('\n') + '\n';
}

// ─────────────────────────────────────────────────────────────────────
//  Helpers — kept private; the builder above is the one public surface.
// ─────────────────────────────────────────────────────────────────────

/**
 * Compute top 3 languages by total LOC across all files.
 * Returns id + integer percentage (0-100). Empty array if no files.
 */
function topLanguages(agent: AgentArtifact): Array<{ id: string; pct: number }> {
  const totals = new Map<string, number>();
  let totalLoc = 0;
  for (const f of agent.files) {
    if (!f.language) continue;
    const loc = f.loc || 0;
    totals.set(f.language, (totals.get(f.language) ?? 0) + loc);
    totalLoc += loc;
  }
  if (totalLoc === 0) return [];
  return [...totals.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([id, loc]) => ({ id, pct: Math.round((loc / totalLoc) * 100) }));
}

/**
 * Files sorted by in-degree (count of edges pointing TO them) descending.
 * Files with in-degree 0 are excluded — they're not hubs by definition.
 */
function topImportedFiles(agent: AgentArtifact, limit: number): Array<{ path: string; inDegree: number }> {
  const inDeg = new Map<string, number>();
  for (const e of agent.graph.edges) {
    inDeg.set(e.to, (inDeg.get(e.to) ?? 0) + 1);
  }
  return [...inDeg.entries()]
    .filter(([, n]) => n > 0)
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, limit)
    .map(([path, inDegree]) => ({ path, inDegree }));
}

/**
 * 5-step deterministic tour. Steps degrade gracefully when their data
 * source is missing — empty projects render "_(none yet)_" placeholders
 * rather than crashing or skipping steps.
 */
function buildTour(agent: AgentArtifact): Array<{ label: string; value: string }> {
  // 1. Manifest — package.json takes priority; fall back to pyproject.toml
  //    or the lowest-depth manifest-ish file.
  const manifestCandidates = ['package.json', 'pyproject.toml', 'Cargo.toml', 'go.mod'];
  const manifest = manifestCandidates.find((c) => agent.files.some((f) => f.path === c));

  // 2. First entry point
  const entry = agent.project.entryPoints[0];

  // 3. Most-imported file
  const top = topImportedFiles(agent, 1)[0];

  // 4. First route handler file
  const firstRoute = agent.routes[0];

  // 5. Sample test (first file with .test. or .spec. or in tests/)
  const sampleTest = agent.files.find(
    (f) => /\.(test|spec)\.[a-z]+$/.test(f.path) || /(^|\/)tests?\//.test(f.path),
  );

  return [
    { label: 'Manifest', value: manifest ? `\`${manifest}\`` : '_(no manifest at root)_' },
    { label: 'Entry', value: entry ? `\`${entry}\`` : '_(no entry point detected)_' },
    { label: 'Most-imported file', value: top ? `\`${top.path}\` (imported by ${top.inDegree})` : '_(no import edges yet)_' },
    { label: 'First route', value: firstRoute ? `\`${firstRoute.handlerFile}\` (${firstRoute.method ?? 'GET'} ${firstRoute.path})` : '_(no routes detected)_' },
    { label: 'Sample test', value: sampleTest ? `\`${sampleTest.path}\`` : '_(no tests detected)_' },
  ];
}

/**
 * Normalize a oneLiner for blockquote rendering:
 *   - collapse all whitespace runs (newlines, tabs, multi-space) to a
 *     single space so the blockquote stays a single line.
 *   - cap at ONELINER_MAX_LEN with a Unicode ellipsis (no markdown
 *     mid-syntax — the truncation point is char-based, not token-aware).
 */
function normalizeOneLiner(s: string): string {
  if (!s) return '_(no description)_';
  const collapsed = s.replace(/\s+/g, ' ').trim();
  if (collapsed.length <= ONELINER_MAX_LEN) return collapsed;
  // Truncate to MAX_LEN-1 to leave room for the ellipsis.
  return collapsed.slice(0, ONELINER_MAX_LEN - 1) + '…';
}

/** US-locale comma-separated number ("43,890"). */
function formatNum(n: number): string {
  // Manual implementation — Intl.NumberFormat is heavy + locale-dependent.
  // Spec: insert a comma every 3 digits from the right.
  const s = String(Math.max(0, Math.floor(n)));
  const parts: string[] = [];
  for (let i = s.length; i > 0; i -= 3) {
    parts.unshift(s.slice(Math.max(0, i - 3), i));
  }
  return parts.join(',');
}

/**
 * Token-count formatter. Drops trailing zeros for tidiness:
 *   530000 → "530K"   1500000 → "1.5M"   999 → "999"
 */
function formatTokens(n: number): string {
  if (n >= 1_000_000) {
    const m = n / 1_000_000;
    return (m % 1 === 0 ? m.toFixed(0) : m.toFixed(1)) + 'M';
  }
  if (n >= 1_000) {
    const k = n / 1_000;
    return (k % 1 === 0 ? k.toFixed(0) : k.toFixed(1)) + 'K';
  }
  return String(Math.floor(n));
}
