/**
 * AGENTS.md renderer — emits `AGENTS.md` at the project root.
 *
 * AGENTS.md is the cross-tool, vendor-neutral convention for "what an AI
 * coding agent should know about this repo." It's read by Codex, Cursor,
 * Zed, Aider, Jules, and a growing list of agents — so it's the format
 * that makes "the agent prefers the FACTS pack" universal rather than
 * tied to one vendor's dotfile.
 *
 * Unlike the per-tool renderers, this one LEADS with the directive that
 * is the entire point of FACTS: before scanning the whole codebase to
 * find code or trace a change, consult `.facts/agent.pack` (or the FACTS
 * MCP). Everything else (stack, hubs, routes, risks) is supporting
 * context.
 *
 * Output path: `AGENTS.md` (single file at root).
 */

import { formatNum, workflowContract } from '../format.js';
import type { SkillRenderer, SkillSpec } from '../types.js';

export const agentsRenderer: SkillRenderer = {
  id: 'agents',
  label: 'AGENTS.md (cross-tool agent guide)',
  render(spec: SkillSpec): Record<string, string> {
    return {
      'AGENTS.md': renderAgentsMd(spec),
    };
  },
};

function renderAgentsMd(spec: SkillSpec): string {
  const lines: string[] = [];

  lines.push('# AGENTS.md');
  lines.push('');
  lines.push(
    `> Machine-readable guide for AI coding agents working in **${spec.name}**. ` +
      'Auto-generated by FACTS.',
  );
  if (spec.intent) {
    lines.push('');
    lines.push(spec.intent);
  }

  /* ── The directive: use the pack, don't re-scan ──────────────────────
       Shared operating contract — identical across every skill format.
       AGENTS.md leads with it; it's the entire point of FACTS. */
  lines.push('');
  lines.push(...workflowContract(spec, 'Before you scan: use the FACTS map'));

  /* ── Project facts ───────────────────────────────────────────────── */
  lines.push('');
  lines.push('## Project');
  lines.push('');
  lines.push(
    `- **Stats**: ${spec.stats.files} files · ${formatNum(spec.stats.loc)} LOC · ${formatNum(spec.stats.tokens)} tokens`,
  );
  if (spec.languages.length) {
    lines.push(`- **Languages**: ${spec.languages.map((l) => `${l.id} (${l.pct}%)`).join(', ')}`);
  }
  if (spec.frameworks.length) {
    lines.push(`- **Frameworks**: ${spec.frameworks.join(', ')}`);
  }
  if (spec.capabilities.length) {
    lines.push(`- **Capabilities**: ${spec.capabilities.join('; ')}`);
  }

  /* ── Entry points ────────────────────────────────────────────────── */
  if (spec.entryPoints.length) {
    lines.push('');
    lines.push('## Entry points');
    lines.push('');
    for (const ep of spec.entryPoints) lines.push(`- \`${ep}\``);
  }

  /* ── Hub files ───────────────────────────────────────────────────── */
  if (spec.keyFiles.length) {
    lines.push('');
    lines.push('## Read these first');
    lines.push('');
    lines.push('Hub files in the import graph — the most-depended-on modules:');
    lines.push('');
    for (const k of spec.keyFiles) {
      lines.push(`- \`${k.path}\` — imported by ${k.inDegree} other files`);
    }
  }

  /* ── Routes ──────────────────────────────────────────────────────── */
  if (spec.routes.length > 0) {
    lines.push('');
    lines.push('## Routes');
    lines.push('');
    for (const r of spec.routes) {
      lines.push(`- ${r.method} \`${r.path}\` (${r.framework})`);
    }
  }

  /* ── Known issues ────────────────────────────────────────────────── */
  if (spec.openRisks.length) {
    lines.push('');
    lines.push('## Known issues');
    lines.push('');
    lines.push('Existing problems — do not regress them:');
    lines.push('');
    for (const r of spec.openRisks) {
      const sev = r.severity === 'critical' ? 'CRITICAL' : 'HIGH';
      const loc = r.file ? ` (\`${r.file}\`)` : '';
      lines.push(`- **${sev}** ${r.category}${loc} — ${r.message}`);
    }
  }

  /* ── Security ────────────────────────────────────────────────────── */
  if (spec.vulnerabilityCount > 0) {
    lines.push('');
    lines.push('## Security');
    lines.push('');
    lines.push(
      `**${spec.vulnerabilityCount}** known dependency ` +
        `${spec.vulnerabilityCount === 1 ? 'vulnerability' : 'vulnerabilities'}. ` +
        'Prefer upgrade versions that resolve them; run `factstack scan-vulns` to refresh.',
    );
  }

  /* ── Conventions ─────────────────────────────────────────────────── */
  lines.push('');
  lines.push('## Conventions');
  lines.push('');
  lines.push('- Match existing file structure + naming when adding code.');
  lines.push('- Prefer extending existing modules over creating new ones unless a real seam justifies it.');

  /* ── Footer ──────────────────────────────────────────────────────── */
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`<!-- Auto-generated by FACTS · factstack ${spec.factsVersion} · ${spec.generatedAt} -->`);
  lines.push('<!-- Refresh: `factstack export-skills --target agents` (or save again from the FACTS web app) -->');

  return lines.join('\n') + '\n';
}
