/**
 * GitHub Copilot Workspace renderer — emits
 * `.github/copilot-instructions.md`.
 *
 * Copilot reads this single file from the `.github/` directory and
 * injects its content into Copilot Chat + Copilot Workspace sessions
 * as system-level project instructions. Same idea as Cursor's
 * `.cursorrules` but with GitHub's convention.
 *
 * Format conventions (from GitHub's docs):
 *   - One markdown file. No YAML frontmatter; the entire file is
 *     treated as instructions.
 *   - First-person plural framing ("we use X", "our codebase is Y")
 *     reads better than imperative — Copilot treats it as project
 *     style/voice.
 *   - Keep it short (GitHub recommends ≤ 4 KB). Anything longer
 *     truncates inconsistently across surfaces (Chat vs Workspace
 *     vs CLI use different limits).
 *
 * Output path: `.github/copilot-instructions.md`
 */

import { formatNum } from '../format.js';
import type { SkillRenderer, SkillSpec } from '../types.js';

export const copilotRenderer: SkillRenderer = {
  id: 'copilot',
  label: 'GitHub Copilot instructions (.github/copilot-instructions.md)',
  render(spec: SkillSpec): Record<string, string> {
    return {
      '.github/copilot-instructions.md': renderCopilotInstructions(spec),
    };
  },
};

function renderCopilotInstructions(spec: SkillSpec): string {
  const lines: string[] = [];

  /* Opener — Copilot's "we" framing. State the project + stack in
     one sentence so the model adopts a coherent project voice. */
  const stack = spec.languages.length
    ? `${spec.languages[0]!.id}`
    : 'this codebase';
  const frameworks = spec.frameworks.length
    ? ` built with ${spec.frameworks.slice(0, 3).join(', ')}`
    : '';
  lines.push(`# ${spec.name}`);
  lines.push('');
  lines.push(`We work in a ${stack} project${frameworks}.`);
  if (spec.intent) {
    lines.push('');
    lines.push(spec.intent);
  }

  /* ── Scale + stack ────────────────────────────────────────────── */
  lines.push('');
  lines.push('## Project shape');
  lines.push('');
  const statsLine = `${spec.stats.files} files, ${formatNum(spec.stats.loc)} LOC, ${formatNum(spec.stats.tokens)} tokens.`;
  lines.push(statsLine);
  if (spec.languages.length) {
    lines.push('');
    lines.push(
      `**Languages**: ${spec.languages.map((l) => `${l.id} ${l.pct}%`).join(', ')}.`,
    );
  }
  if (spec.frameworks.length) {
    lines.push(`**Frameworks**: ${spec.frameworks.join(', ')}.`);
  }

  /* ── Capabilities ─────────────────────────────────────────────── */
  if (spec.capabilities.length) {
    lines.push('');
    lines.push('## What this project does');
    lines.push('');
    for (const cap of spec.capabilities) lines.push(`- ${cap}`);
  }

  /* ── Entry points ─────────────────────────────────────────────── */
  if (spec.entryPoints.length) {
    lines.push('');
    lines.push('## Entry points');
    lines.push('');
    for (const ep of spec.entryPoints) lines.push(`- \`${ep}\``);
  }

  /* ── Key files (terse — Copilot Workspace's UI doesn't render
       multi-paragraph file lists well) ───────────────────────────── */
  if (spec.keyFiles.length) {
    lines.push('');
    lines.push('## Key files');
    lines.push('');
    lines.push("Start here when exploring:");
    lines.push('');
    for (const k of spec.keyFiles) lines.push(`- \`${k.path}\``);
  }

  /* ── Risks (de-emphasize severity icons — Copilot stripping
       sometimes mangles them; use plain text) ────────────────────── */
  if (spec.openRisks.length) {
    lines.push('');
    lines.push('## Known issues to avoid regressing');
    lines.push('');
    for (const r of spec.openRisks) {
      const sev = r.severity === 'critical' ? '[CRITICAL]' : '[HIGH]';
      const loc = r.file ? ` (\`${r.file}\`)` : '';
      lines.push(`- ${sev} ${r.category}${loc} — ${r.message}`);
    }
  }

  /* ── Vulnerabilities ──────────────────────────────────────────── */
  if (spec.vulnerabilityCount > 0) {
    lines.push('');
    lines.push('## Security');
    lines.push('');
    lines.push(
      `This project has ${spec.vulnerabilityCount} known ` +
        `${spec.vulnerabilityCount === 1 ? 'vulnerability' : 'vulnerabilities'} ` +
        'in declared dependencies. When suggesting upgrades, prefer the patched versions.',
    );
  }

  /* ── Conventions ──────────────────────────────────────────────── */
  lines.push('');
  lines.push('## Conventions');
  lines.push('');
  lines.push('- Match existing file and naming patterns when adding code.');
  lines.push('- Prefer extending existing modules over creating new ones.');
  lines.push(
    '- Keep diffs minimal and revertable — one concern per commit.',
  );

  /* ── Footer ───────────────────────────────────────────────────── */
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(
    `*Auto-generated by FACTS (factstack ${spec.factsVersion}, ${spec.generatedAt}). Refresh: \`factstack export-skills --target copilot\`.*`,
  );

  return lines.join('\n') + '\n';
}
